// <auto-generated />
namespace Projeto_Solidario_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DadosIniciais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DadosIniciais));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081549211_DadosIniciais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
